spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/advancespring
    username: root
    password: ghks9430
    hikari:
      auto-commit: true

jwt:
  secret:
    key: vDLW2ZV+RkZIb8OM8Oq3oBqV3yZ3hUqjPlAEX1zjK3M=
